INSERT INTO `jouer` (`titre_film`, `code_indiv`) VALUES
('Avatar',1),
('Avatar',2),
('Titanic',3),
('Titanic',4),
('Avengers:Infinity War',5),
('Avengers:Infinity War',6),
('Jurassic World',7),
('Jurassic World',8),
('Avengers',6),
('Avengers',9),
('Fast and Furious 7',10),
('Fast and Furious 7',11),
('Black Panther',12),
('Black Panther',13),
('La reine des neiges',14),
('La reine des neiges',15),
('Iron Man 3',6),
('Iron Man 3',16),
('Les Indestructibles 2',17),
('Les Indestructibles 2',18),
('Les gardiens de la Galaxie',7),
('Les gardiens de la Galaxie',2);